// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package sys

import (
	internal "exam/internal/dao/sys/internal"
)

// sysAuditChangeDetailDao is the data access object for the table sys_audit_change_detail.
// You can define custom methods on it to extend its functionality as needed.
type sysAuditChangeDetailDao struct {
	*internal.SysAuditChangeDetailDao
}

var (
	// SysAuditChangeDetail is a globally accessible object for table sys_audit_change_detail operations.
	SysAuditChangeDetail = sysAuditChangeDetailDao{internal.NewSysAuditChangeDetailDao()}
)

// Add your custom methods and functionality below.
