// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package sys

import (
	internal "exam/internal/dao/sys/internal"
)

// sysFileChunkUploadDao is the data access object for the table sys_file_chunk_upload.
// You can define custom methods on it to extend its functionality as needed.
type sysFileChunkUploadDao struct {
	*internal.SysFileChunkUploadDao
}

var (
	// SysFileChunkUpload is a globally accessible object for table sys_file_chunk_upload operations.
	SysFileChunkUpload = sysFileChunkUploadDao{internal.NewSysFileChunkUploadDao()}
)

// Add your custom methods and functionality below.
