// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package sys

import (
	internal "exam/internal/dao/sys/internal"
)

// sysTaskDao is the data access object for the table sys_task.
// You can define custom methods on it to extend its functionality as needed.
type sysTaskDao struct {
	*internal.SysTaskDao
}

var (
	// SysTask is a globally accessible object for table sys_task operations.
	SysTask = sysTaskDao{internal.NewSysTaskDao()}
)

// Add your custom methods and functionality below.
