// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package sys

import (
	internal "exam/internal/dao/sys/internal"
)

// sysNotificationChannelConfigDao is the data access object for the table sys_notification_channel_config.
// You can define custom methods on it to extend its functionality as needed.
type sysNotificationChannelConfigDao struct {
	*internal.SysNotificationChannelConfigDao
}

var (
	// SysNotificationChannelConfig is a globally accessible object for table sys_notification_channel_config operations.
	SysNotificationChannelConfig = sysNotificationChannelConfigDao{internal.NewSysNotificationChannelConfigDao()}
)

// Add your custom methods and functionality below.
