// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package sys

import (
	internal "exam/internal/dao/sys/internal"
)

// sysSecurityEventLogDao is the data access object for the table sys_security_event_log.
// You can define custom methods on it to extend its functionality as needed.
type sysSecurityEventLogDao struct {
	*internal.SysSecurityEventLogDao
}

var (
	// SysSecurityEventLog is a globally accessible object for table sys_security_event_log operations.
	SysSecurityEventLog = sysSecurityEventLogDao{internal.NewSysSecurityEventLogDao()}
)

// Add your custom methods and functionality below.
