// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package sys

import (
	internal "exam/internal/dao/sys/internal"
)

// sysTaskLogDao is the data access object for the table sys_task_log.
// You can define custom methods on it to extend its functionality as needed.
type sysTaskLogDao struct {
	*internal.SysTaskLogDao
}

var (
	// SysTaskLog is a globally accessible object for table sys_task_log operations.
	SysTaskLog = sysTaskLogDao{internal.NewSysTaskLogDao()}
)

// Add your custom methods and functionality below.
