// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package sys

import (
	internal "exam/internal/dao/sys/internal"
)

// sysNotificationLogDao is the data access object for the table sys_notification_log.
// You can define custom methods on it to extend its functionality as needed.
type sysNotificationLogDao struct {
	*internal.SysNotificationLogDao
}

var (
	// SysNotificationLog is a globally accessible object for table sys_notification_log operations.
	SysNotificationLog = sysNotificationLogDao{internal.NewSysNotificationLogDao()}
)

// Add your custom methods and functionality below.
