// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package sys

import (
	internal "exam/internal/dao/sys/internal"
)

// sysPasswordHistoryDao is the data access object for the table sys_password_history.
// You can define custom methods on it to extend its functionality as needed.
type sysPasswordHistoryDao struct {
	*internal.SysPasswordHistoryDao
}

var (
	// SysPasswordHistory is a globally accessible object for table sys_password_history operations.
	SysPasswordHistory = sysPasswordHistoryDao{internal.NewSysPasswordHistoryDao()}
)

// Add your custom methods and functionality below.
