// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package sys

import (
	internal "exam/internal/dao/sys/internal"
)

// sysExceptionLogDao is the data access object for the table sys_exception_log.
// You can define custom methods on it to extend its functionality as needed.
type sysExceptionLogDao struct {
	*internal.SysExceptionLogDao
}

var (
	// SysExceptionLog is a globally accessible object for table sys_exception_log operations.
	SysExceptionLog = sysExceptionLogDao{internal.NewSysExceptionLogDao()}
)

// Add your custom methods and functionality below.
