// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package sys

import (
	internal "exam/internal/dao/sys/internal"
)

// sysOperationAuditLogDao is the data access object for the table sys_operation_audit_log.
// You can define custom methods on it to extend its functionality as needed.
type sysOperationAuditLogDao struct {
	*internal.SysOperationAuditLogDao
}

var (
	// SysOperationAuditLog is a globally accessible object for table sys_operation_audit_log operations.
	SysOperationAuditLog = sysOperationAuditLogDao{internal.NewSysOperationAuditLogDao()}
)

// Add your custom methods and functionality below.
