// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package sys

import (
	internal "exam/internal/dao/sys/internal"
)

// sysMemberDao is the data access object for the table sys_member.
// You can define custom methods on it to extend its functionality as needed.
type sysMemberDao struct {
	*internal.SysMemberDao
}

var (
	// SysMember is a globally accessible object for table sys_member operations.
	SysMember = sysMemberDao{internal.NewSysMemberDao()}
)

// Add your custom methods and functionality below.
