// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package sys

import (
	internal "exam/internal/dao/sys/internal"
)

// sysFileStorageDao is the data access object for the table sys_file_storage.
// You can define custom methods on it to extend its functionality as needed.
type sysFileStorageDao struct {
	*internal.SysFileStorageDao
}

var (
	// SysFileStorage is a globally accessible object for table sys_file_storage operations.
	SysFileStorage = sysFileStorageDao{internal.NewSysFileStorageDao()}
)

// Add your custom methods and functionality below.
