// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package sys

import (
	internal "exam/internal/dao/sys/internal"
)

// sysNotificationTemplateDao is the data access object for the table sys_notification_template.
// You can define custom methods on it to extend its functionality as needed.
type sysNotificationTemplateDao struct {
	*internal.SysNotificationTemplateDao
}

var (
	// SysNotificationTemplate is a globally accessible object for table sys_notification_template operations.
	SysNotificationTemplate = sysNotificationTemplateDao{internal.NewSysNotificationTemplateDao()}
)

// Add your custom methods and functionality below.
