// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package sys

import (
	internal "exam/internal/dao/sys/internal"
)

// sysFileStorageConfigDao is the data access object for the table sys_file_storage_config.
// You can define custom methods on it to extend its functionality as needed.
type sysFileStorageConfigDao struct {
	*internal.SysFileStorageConfigDao
}

var (
	// SysFileStorageConfig is a globally accessible object for table sys_file_storage_config operations.
	SysFileStorageConfig = sysFileStorageConfigDao{internal.NewSysFileStorageConfigDao()}
)

// Add your custom methods and functionality below.
