// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package mock

import (
	internal "exam/internal/dao/mock/internal"
)

// mockExaminationPartDao is the data access object for the table mock_examination_part.
// You can define custom methods on it to extend its functionality as needed.
type mockExaminationPartDao struct {
	*internal.MockExaminationPartDao
}

var (
	// MockExaminationPart is a globally accessible object for table mock_examination_part operations.
	MockExaminationPart = mockExaminationPartDao{internal.NewMockExaminationPartDao()}
)

// Add your custom methods and functionality below.
