// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package mock

import (
	internal "exam/internal/dao/mock/internal"
)

// mockLevelsDao is the data access object for the table mock_levels.
// You can define custom methods on it to extend its functionality as needed.
type mockLevelsDao struct {
	*internal.MockLevelsDao
}

var (
	// MockLevels is a globally accessible object for table mock_levels operations.
	MockLevels = mockLevelsDao{internal.NewMockLevelsDao()}
)

// Add your custom methods and functionality below.
