// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package mock

import (
	internal "exam/internal/dao/mock/internal"
)

// mockExaminationSegmentDao is the data access object for the table mock_examination_segment.
// You can define custom methods on it to extend its functionality as needed.
type mockExaminationSegmentDao struct {
	*internal.MockExaminationSegmentDao
}

var (
	// MockExaminationSegment is a globally accessible object for table mock_examination_segment operations.
	MockExaminationSegment = mockExaminationSegmentDao{internal.NewMockExaminationSegmentDao()}
)

// Add your custom methods and functionality below.
