// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package mock

import (
	internal "exam/internal/dao/mock/internal"
)

// mockExaminationPaperDao is the data access object for the table mock_examination_paper.
// You can define custom methods on it to extend its functionality as needed.
type mockExaminationPaperDao struct {
	*internal.MockExaminationPaperDao
}

var (
	// MockExaminationPaper is a globally accessible object for table mock_examination_paper operations.
	MockExaminationPaper = mockExaminationPaperDao{internal.NewMockExaminationPaperDao()}
)

// Add your custom methods and functionality below.
