// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package exam

import (
	"exam/internal/dao/exam/internal"
)

// examOptionDao is the data access object for the table exam_option.
// You can define custom methods on it to extend its functionality as needed.
type examOptionDao struct {
	*internal.ExamOptionDao
}

var (
	// ExamOption is a globally accessible object for table exam_option operations.
	ExamOption = examOptionDao{internal.NewExamOptionDao()}
)

// Add your custom methods and functionality below.
