// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package exam

import (
	"exam/internal/dao/exam/internal"
)

// examBatchMockLevelDao is the data access object for the table exam_batch_mock_level.
// You can define custom methods on it to extend its functionality as needed.
type examBatchMockLevelDao struct {
	*internal.ExamBatchMockLevelDao
}

var (
	// ExamBatchMockLevel is a globally accessible object for table exam_batch_mock_level operations.
	ExamBatchMockLevel = examBatchMockLevelDao{internal.NewExamBatchMockLevelDao()}
)

// Add your custom methods and functionality below.
