// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package exam

import (
	"exam/internal/dao/exam/internal"
)

// examBatchDao is the data access object for the table exam_batch.
// You can define custom methods on it to extend its functionality as needed.
type examBatchDao struct {
	*internal.ExamBatchDao
}

var (
	// ExamBatch is a globally accessible object for table exam_batch operations.
	ExamBatch = examBatchDao{internal.NewExamBatchDao()}
)

// Add your custom methods and functionality below.
