// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package exam

import (
	internal "exam/internal/dao/exam/internal"
)

// examAttemptAnswerDao is the data access object for the table exam_attempt_answer.
// You can define custom methods on it to extend its functionality as needed.
type examAttemptAnswerDao struct {
	*internal.ExamAttemptAnswerDao
}

var (
	// ExamAttemptAnswer is a globally accessible object for table exam_attempt_answer operations.
	ExamAttemptAnswer = examAttemptAnswerDao{internal.NewExamAttemptAnswerDao()}
)

// Add your custom methods and functionality below.
