// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package exam

import (
	internal "exam/internal/dao/exam/internal"
)

// examQuestionBlockDao is the data access object for the table exam_question_block.
// You can define custom methods on it to extend its functionality as needed.
type examQuestionBlockDao struct {
	*internal.ExamQuestionBlockDao
}

var (
	// ExamQuestionBlock is a globally accessible object for table exam_question_block operations.
	ExamQuestionBlock = examQuestionBlockDao{internal.NewExamQuestionBlockDao()}
)

// Add your custom methods and functionality below.
