// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package exam

import (
	"exam/internal/dao/exam/internal"
)

// examBatchMemberDao is the data access object for the table exam_batch_member.
// You can define custom methods on it to extend its functionality as needed.
type examBatchMemberDao struct {
	*internal.ExamBatchMemberDao
}

var (
	// ExamBatchMember is a globally accessible object for table exam_batch_member operations.
	ExamBatchMember = examBatchMemberDao{internal.NewExamBatchMemberDao()}
)

// Add your custom methods and functionality below.
