// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package exam

import (
	"exam/internal/dao/exam/internal"
)

// examQuestionDao is the data access object for the table exam_question.
// You can define custom methods on it to extend its functionality as needed.
type examQuestionDao struct {
	*internal.ExamQuestionDao
}

var (
	// ExamQuestion is a globally accessible object for table exam_question operations.
	ExamQuestion = examQuestionDao{internal.NewExamQuestionDao()}
)

// Add your custom methods and functionality below.
