// ================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// ================================================================================

package exam

import (
	"exam/internal/dao/exam/internal"
)

// examAttemptCheatEventDao is the data access object for the table exam_attempt_cheat_event.
// You can define custom methods on it to extend its functionality as needed.
type examAttemptCheatEventDao struct {
	*internal.ExamAttemptCheatEventDao
}

var (
	// ExamAttemptCheatEvent is a globally accessible object for table exam_attempt_cheat_event operations.
	ExamAttemptCheatEvent = examAttemptCheatEventDao{internal.NewExamAttemptCheatEventDao()}
)

// Add your custom methods and functionality below.
