// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package exam

import (
	"exam/internal/dao/exam/internal"
)

// examBatchPaperDao is the data access object for the table exam_batch_paper.
// You can define custom methods on it to extend its functionality as needed.
type examBatchPaperDao struct {
	*internal.ExamBatchPaperDao
}

var (
	// ExamBatchPaper is a globally accessible object for table exam_batch_paper operations.
	ExamBatchPaper = examBatchPaperDao{internal.NewExamBatchPaperDao()}
)

// Add your custom methods and functionality below.
