// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package exam

import (
	internal "exam/internal/dao/exam/internal"
)

// examAttemptDao is the data access object for the table exam_attempt.
// You can define custom methods on it to extend its functionality as needed.
type examAttemptDao struct {
	*internal.ExamAttemptDao
}

var (
	// ExamAttempt is a globally accessible object for table exam_attempt operations.
	ExamAttempt = examAttemptDao{internal.NewExamAttemptDao()}
)

// Add your custom methods and functionality below.
