// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package exam

import (
	internal "exam/internal/dao/exam/internal"
)

// examAttemptQuestionAudioDao is the data access object for the table exam_attempt_question_audio.
// You can define custom methods on it to extend its functionality as needed.
type examAttemptQuestionAudioDao struct {
	*internal.ExamAttemptQuestionAudioDao
}

var (
	// ExamAttemptQuestionAudio is a globally accessible object for table exam_attempt_question_audio operations.
	ExamAttemptQuestionAudio = examAttemptQuestionAudioDao{internal.NewExamAttemptQuestionAudioDao()}
)

// Add your custom methods and functionality below.
