// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package exam

import (
	"exam/internal/dao/exam/internal"
)

// examPaperDao is the data access object for the table exam_paper.
// You can define custom methods on it to extend its functionality as needed.
type examPaperDao struct {
	*internal.ExamPaperDao
}

var (
	// ExamPaper is a globally accessible object for table exam_paper operations.
	ExamPaper = examPaperDao{internal.NewExamPaperDao()}
)

// Add your custom methods and functionality below.
