// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package exam

import (
	internal "exam/internal/dao/exam/internal"
)

// examSectionDao is the data access object for the table exam_section.
// You can define custom methods on it to extend its functionality as needed.
type examSectionDao struct {
	*internal.ExamSectionDao
}

var (
	// ExamSection is a globally accessible object for table exam_section operations.
	ExamSection = examSectionDao{internal.NewExamSectionDao()}
)

// Add your custom methods and functionality below.
